[package]
name = "code_builder"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0"
anyhow = "1.0"
log = "0.4"
serde = { version = "1", features = ["derive"] }
bollard = "0.13"
async-trait = "0.1"
semver = "1.0"
