name = "vscode"
main = "src/worker.ts"
compatibility_date = "2023-08-20"

[env.staging]
vars = { ENVIRONMENT = "staging" }
routes = [ { pattern = "staging.vscode.luxass.dev", custom_domain = true } ]

[env.production]
vars = { ENVIRONMENT = "production" }
routes = [ { pattern = "vscode.luxass.dev", custom_domain = true } ]
