[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
log = "0.4"
schema_core = { path = "../schema-core" }
code_builder = { path = "../code-builder" }