name: Build Schema CLI

on:
  push:
    paths:
      - '.github/workflows/**'
      - 'crates/**/*'
      - 'Cargo.toml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          cargo build --verbose --release
      - name: Create artifact directory
        run: mkdir artifacts
      - name: Copy files
        run: |
          cp target/release/cli artifacts/
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: vscode-schema
          path: artifacts/

