name: Generate Schemas

on:
  pull_request:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        run: |
          echo "Hey"
      # - name: Setup deno
      #   uses: denoland/setup-deno@v1
      #   with:
      #     deno-version: v1.x

      # - name: Add Permissions
      #   run: |
      #     chmod +x ./src/main.ts
      #     chmod +x ./scripts/write-list.ts
      #     chmod +x ./scripts/run-all-generate.ts
      #     chmod +x ./scripts/run-all-scans.ts

      # - name: Download Source Code
      #   run: ./src/main.ts download --out vscode

      # - name: Scan for Schemas
      #   run: ./src/main.ts scan --default-out --code-src vscode

      # - name: Generate Schemas
      #   run: ./src/main.ts generate --code-src vscode

      # - name: Update Schemas README & Write .schemas-list.json
      #   run: ./scripts/write-list.ts
