name: Generate Schemas

on:
  workflow_run:
    workflows: ["Build Schema CLI"]
    types:
      - completed
  schedule:
    - cron: "0 */6 * * *"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download Schema CLI
        id: download-schema-cli
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          name: vscode-schema
          path: artifacts/
      - name: Make it executable
        run: chmod +x artifacts/vscode-schema
      - name: Refetch Schemas
        run: |
          ./artifacts/schema-gen refetch --metadata-url metadata.json
      - name: Generate Schemas
        run: |
          echo $GITHUB_WORKSPACE
          ./artifacts/schema-gen generate --metadata-url metadata.json --dir /home/runner/work/vscode-schemas/vscode-schemas
