name: Generate Schemas

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Generate Schemas
        run: deno run --allow-read --allow-write --allow-net --allow-env --unstable ./src/main.ts --help
