name: Generate Schemas
on:
  push:
  schedule:
    - cron:  '0 */6 * * *'


jobs:
  download-driver:
    runs-on: ubuntu-latest
    steps:
      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version
  # run:
  #   needs: download-driver
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Run
  #       run: |
  #         cd schema-gen
  #         cargo run --release
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

