name: Generate Schemas
on:
  push:
  schedule:
    - cron:  '0 */6 * * *'


jobs:
  deno:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Run deno
        run: deno run --allow-read --allow-write --allow-net --allow-env --unstable ./scripts/generate-schemas.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

