name: Generate Schemas
on:
  push:
  schedule:
    - cron:  '0 */6 * * *'


jobs:
  build-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run
        run: |
          cd scanner
          cargo run --
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

