name: Deploy to Cloudflare Workers

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: Run the workflow without creating a deployment
        required: false
        type: boolean
        default: false
      environment:
        description: The environment to deploy to
        required: true
        options:
          - staging
          - production
        type: choice
        default: 'staging'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

# You can leverage Vercel Remote Caching with Turbo to speed up your builds
# @link https://turborepo.org/docs/core-concepts/remote-caching#remote-caching-on-vercel-builds
env:
  FORCE_COLOR: 3
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Lint
        run: pnpm lint

      - name: Typecheck
        run: pnpm typecheck

  deploy-staging:
    runs-on: ubuntu-latest
    needs: ci
    if: (github.event.inputs.environment == 'staging' || github.event_name == 'pull_request') && github.repository == 'luxass/vscode-schemas' && contains(fromJson(vars.DEPLOY_ALLOWLIST), github.actor)
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: pnpm install

      - name: Deploy
        if: ${{ github.event.inputs.dry-run != 'true' }}
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          packageManager: pnpm
          environment: staging

  deploy-production:
    runs-on: ubuntu-latest
    needs: ci
    if: (github.event.inputs.environment == 'production' || github.event_name == 'push') && github.repository == 'luxass/vscode-schemas' && contains(fromJson(vars.DEPLOY_ALLOWLIST), github.actor)
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: pnpm install

      - name: Deploy
        if: ${{ github.event.inputs.dry-run != 'true' }}
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          packageManager: pnpm
          environment: production
